name: HTML to PDF Conversion

on:
  push:
    branches:
      - jupyterbook
  pull_request:
    branches:
      - jupyterbook

jobs:
  convert_html_to_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare output directory
      run: mkdir -p docs/output

    - name: Combine HTML files
      run: |
        # Find and concatenate all HTML files under docs/Lecture notes
        find docs/Lecture\ notes -type f -name "*.html" -exec cat {} + > docs/output/combined.html

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install WeasyPrint
      run: |
        pip install weasyprint

    - name: Convert HTML to PDF
      run: |
        # Convert combined HTML to PDF
        weasyprint docs/output/combined.html docs/output/combined.pdf

    - name: Upload PDF as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-pdf
        path: docs/output/combined.pdf
